'use strict';

module.exports = {
  PROJ_NAME: 'workflow',
  HOME_DIR_LOG: 'logs',
  PLUGIN_PREFIX: 'workflow-plugin-',
  PLUGIN_TYPE_INIT: 'init',
  NOTFOUNDVERSION: -1,
  BUILD_TYPE_DEV: 'dev',
  BUILD_TYPE_BUILD: 'build',
  WORKFLOW_CONFIG_FILE: 'workflow.js',
  ERR: {
    UNKNOWN_ERR: 1001,
    NODE_VERSION_ERR: 1002,
    INIT_CLIENT_ERR: 1003,
    UPGRADE_ERR: 1004,
    PLUGIN_UPDATE_ERR: 1005,
    NO_PLUGIN_ERR: 1006,

    INIT_NO_PLUGIN_ERR: 2001,
    INIT_INSTALL_ERR: 2002,
    INIT_YO_ERR: 2003,

    BUILD_LOAD_CONFIG_ERR: 3001,
    BUILD_NO_PLUGIN_ERR: 3002,
    BUILD_INSTALL_ERR: 3003,
    BUILD_RUN_ERR: 3004,
  },
};
